require 'xi/core_ext/array'
require 'xi/core_ext/enumerable'
require 'xi/core_ext/enumerator'
require 'xi/core_ext/integer'
require 'xi/core_ext/numeric'
require 'xi/core_ext/object'
require 'xi/core_ext/scalar'
require 'xi/core_ext/string'
